const collection = require('../utilities/connections');

const userDb = [
    {
        "name": "Rahul",
        "mobNo": "8787767887",
        "emailId": "rahul@gmail.com",
        "password": "Rahul@12345",
        "id": 1001
    },
    {
        "name": "Chandan",
        "mobNo": "9878987678",
        "emailId": "chandan@gmail.com",
        "password": "Chandan@12345",
        "id": 1002
    },
    {
        "name": "Akshay",
        "mobNo": "8977688768",
        "emailId": "akshay@gmail.com",
        "password": "Akshay@12345",
        "id": 1003
    }
]

const bookings = [
    {
        "propertyId": "P1001",
        "name": "Rahul",
        "mobNo": "9888787898",
        "emailId": "rahul@gmail.com",
        "pancardNo": "NHVFR5432W",
        "visitingDate": "2021-25-12",
        "sellerId": "U1001",
        "id": 1
    },
    {
        "propertyId": "P1002",
        "name": "Chandan",
        "mobNo": "9878976787",
        "emailId": "chandan@gmail.com",
        "pancardNo": "NBHYB5432R",
        "visitingDate": "2021-26-12",
        "sellerId": "U1001",
        "id": 2
    },
    {
        "propertyId": "P1002",
        "name": "Akshay",
        "mobNo": "9878908778",
        "emailId": "akshay@gmail.com",
        "pancardNo": "NREDC7654L",
        "visitingDate": "2021-30-12",
        "sellerId": "U1001",
        "id": 3
    }
]

const propertyDb = [
    {
        "id": 1,
        "propertyId": "P1001",
        "sellerId": "U1001",
        "visitors": [
            1001
        ],
        "pincode": 570001,
        "propertyType": "Rent",
        "propertyOwnership": "Owner",
        "buildingType": "House",
        "noOfBathrooms": 2,
        "noOfBedrooms": 2,
        "noOfBalconies": 1,
        "furnishing": "Fully Furnished",
        "availability": "Ready to move",
        "lifts": true,
        "ac": true,
        "heater": false,
        "maintenenceStaff": true,
        "visitorParking": true,
        "IntercomFacility": false,
        "wifi": true,
        "fireAlarm": false,
        "WaterPurifier": false,
        "PowerBackup": true,
        "WaterSupplyFor24Hours": true,
        "CloseToSchool": true,
        "CloseToHospital": false,
        "CloseToRailwayStation": true,
        "CloseToBusStand": true,
        "CloseToAirport": false,
        "CloseToBank": true,
        "CloseToPark": false,
        "status": "Available",
        "address": "196,12th Street,Delhi",
        "price": 15000,
        "Advance": 50000,
        "transactionType": "New",
        "ageOfProperty": "1 year old property",
        "availabilityBy": "Within 2 weeks",
        "totalFloors": 10,
        "PropertyFloor": 5,
        "propertyArea": 1200,
        "poojaRoom": true,
        "servantRoonm": true,
        "noofCoveredParking": 1,
        "noOfOpenParking": 1,
        "description": "Recently renovated and restored. Upper Unit - 2 Bedrooms 2 Full Bathroom - New kitchen, appliances, bathroom and flooring - Kitchen appliances included: Refrigerator, Gas Oven/ Range, Dishwasher, Over the Range Microwave - Private Washer and Dryer - 2 driveway parking spaces - All Bedrooms have large closets - 2 minute walk from village center: Restaurants, cafes, shops, bars, festivals, farmers market - Tenant pays Gas and Electricity - Available Immediately - Sorry, no pets Tenant pays gas and electricity",
        "imageUrls": "./assets/house1.jpg",
        "extras": "Pets are not allowed"
    },
    {
        "id": 2,
        "propertyId": "P1002",
        "sellerId": "U1001",
        "visitors": [
            1002,
            1003
        ],
        "pincode": 570017,
        "propertyType": "Rent",
        "propertyOwnership": "Owner",
        "buildingType": "House",
        "noOfBathrooms": 1,
        "noOfBedrooms": 2,
        "noOfBalconies": 1,
        "furnishing": "Fully Furnished",
        "availability": "Ready to move",
        "lifts": true,
        "ac": true,
        "heater": false,
        "maintenenceStaff": true,
        "visitorParking": true,
        "IntercomFacility": false,
        "wifi": true,
        "fireAlarm": false,
        "WaterPurifier": false,
        "PowerBackup": true,
        "WaterSupplyFor24Hours": true,
        "CloseToSchool": true,
        "CloseToHospital": false,
        "CloseToRailwayStation": true,
        "CloseToBusStand": true,
        "CloseToAirport": false,
        "CloseToBank": true,
        "CloseToPark": false,
        "status": "Available",
        "address": "Sector 8,Ram colony,Noida",
        "price": 9000,
        "Advance": 30000,
        "transactionType": "New",
        "ageOfProperty": "1 year old property",
        "availabilityBy": "Within 2 weeks",
        "totalFloors": 10,
        "PropertyFloor": 5,
        "propertyArea": 900,
        "poojaRoom": true,
        "servantRoonm": true,
        "noofCoveredParking": 1,
        "noOfOpenParking": 1,
        "description": "Recently renovated and restored. Upper Unit - 2 Bedrooms 2 Full Bathroom - New kitchen, appliances, bathroom and flooring - Kitchen appliances included: Refrigerator, Gas Oven/ Range, Dishwasher, Over the Range Microwave - Private Washer and Dryer - 2 driveway parking spaces - All Bedrooms have large closets - 2 minute walk from village center: Restaurants, cafes, shops, bars, festivals, farmers market - Tenant pays Gas and Electricity - Available Immediately - Sorry, no pets Tenant pays gas and electricity",
        "imageUrls": "./assets/house2.jpg",
        "extras": "Pets are not allowed"
    },
    {
        "id": 3,
        "propertyId": "P1003",
        "sellerId": "U1002",
        "visitors": [],
        "pincode": 570017,
        "propertyType": "Sale",
        "propertyOwnership": "Owner",
        "buildingType": "House",
        "noOfBathrooms": 2,
        "noOfBedrooms": 2,
        "noOfBalconies": 1,
        "furnishing": "Fully Furnished",
        "availability": "Ready to move",
        "lifts": true,
        "ac": true,
        "heater": false,
        "maintenenceStaff": true,
        "visitorParking": true,
        "IntercomFacility": false,
        "wifi": true,
        "fireAlarm": false,
        "WaterPurifier": false,
        "PowerBackup": true,
        "WaterSupplyFor24Hours": true,
        "CloseToSchool": true,
        "CloseToHospital": false,
        "CloseToRailwayStation": true,
        "CloseToBusStand": true,
        "CloseToAirport": false,
        "CloseToBank": true,
        "CloseToPark": false,
        "status": "Available",
        "address": "136,15th Street,Mumbai",
        "price": 120000,
        "Advance": 50000,
        "transactionType": "New",
        "ageOfProperty": "1 year old property",
        "availabilityBy": "Within 2 weeks",
        "totalFloors": 10,
        "PropertyFloor": 5,
        "propertyArea": 1000,
        "poojaRoom": true,
        "servantRoonm": true,
        "noofCoveredParking": 1,
        "noOfOpenParking": 1,
        "description": "Recently renovated and restored. Upper Unit - 2 Bedrooms 2 Full Bathroom - New kitchen, appliances, bathroom and flooring - Kitchen appliances included: Refrigerator, Gas Oven/ Range, Dishwasher, Over the Range Microwave - Private Washer and Dryer - 2 driveway parking spaces - All Bedrooms have large closets - 2 minute walk from village center: Restaurants, cafes, shops, bars, festivals, farmers market - Tenant pays Gas and Electricity - Available Immediately - Sorry, no pets Tenant pays gas and electricity",
        "imageUrls": "./assets/house1.jpg",
        "extras": "Pets are not allowed"
    },
    {
        "id": 4,
        "propertyId": "P1004",
        "sellerId": "U1001",
        "visitors": [],
        "pincode": 570017,
        "propertyType": "Rent",
        "propertyOwnership": "Owner",
        "buildingType": "House",
        "noOfBathrooms": 1,
        "noOfBedrooms": 2,
        "noOfBalconies": 1,
        "furnishing": "Fully Furnished",
        "availability": "Ready to move",
        "lifts": true,
        "ac": true,
        "heater": false,
        "maintenenceStaff": true,
        "visitorParking": true,
        "IntercomFacility": false,
        "wifi": true,
        "fireAlarm": false,
        "WaterPurifier": false,
        "PowerBackup": true,
        "WaterSupplyFor24Hours": true,
        "CloseToSchool": true,
        "CloseToHospital": false,
        "CloseToRailwayStation": true,
        "CloseToBusStand": true,
        "CloseToAirport": false,
        "CloseToBank": true,
        "CloseToPark": false,
        "status": "Available",
        "address": "Street 2,Hebbal colony,Mysore",
        "price": 9000,
        "Advance": 30000,
        "transactionType": "New",
        "ageOfProperty": "1 year old property",
        "availabilityBy": "Within 2 weeks",
        "totalFloors": 10,
        "PropertyFloor": 5,
        "propertyArea": 900,
        "poojaRoom": true,
        "servantRoonm": true,
        "noofCoveredParking": 1,
        "noOfOpenParking": 1,
        "description": "Recently renovated and restored. Upper Unit - 2 Bedrooms 2 Full Bathroom - New kitchen, appliances, bathroom and flooring - Kitchen appliances included: Refrigerator, Gas Oven/ Range, Dishwasher, Over the Range Microwave - Private Washer and Dryer - 2 driveway parking spaces - All Bedrooms have large closets - 2 minute walk from village center: Restaurants, cafes, shops, bars, festivals, farmers market - Tenant pays Gas and Electricity - Available Immediately - Sorry, no pets Tenant pays gas and electricity",
        "imageUrls": "./assets/house2.jpg",
        "extras": "Pets are not allowed"
    },
    {
        "id": 5,
        "propertyId": "P1005",
        "sellerId": "U1002",
        "visitors": [],
        "pincode": 570017,
        "propertyType": "Sale",
        "propertyOwnership": "Owner",
        "buildingType": "House",
        "noOfBathrooms": 2,
        "noOfBedrooms": 2,
        "noOfBalconies": 1,
        "furnishing": "Fully Furnished",
        "availability": "Ready to move",
        "lifts": true,
        "ac": true,
        "heater": false,
        "maintenenceStaff": true,
        "visitorParking": true,
        "IntercomFacility": false,
        "wifi": true,
        "fireAlarm": false,
        "WaterPurifier": false,
        "PowerBackup": true,
        "WaterSupplyFor24Hours": true,
        "CloseToSchool": true,
        "CloseToHospital": false,
        "CloseToRailwayStation": true,
        "CloseToBusStand": true,
        "CloseToAirport": false,
        "CloseToBank": true,
        "CloseToPark": false,
        "status": "Available",
        "address": "Super market,near Railway station,Gurgaon",
        "price": 120000,
        "Advance": 50000,
        "transactionType": "New",
        "ageOfProperty": "1 year old property",
        "availabilityBy": "Within 2 weeks",
        "totalFloors": 10,
        "PropertyFloor": 5,
        "propertyArea": 1000,
        "poojaRoom": true,
        "servantRoonm": true,
        "noofCoveredParking": 1,
        "noOfOpenParking": 1,
        "description": "Recently renovated and restored. Upper Unit - 2 Bedrooms 2 Full Bathroom - New kitchen, appliances, bathroom and flooring - Kitchen appliances included: Refrigerator, Gas Oven/ Range, Dishwasher, Over the Range Microwave - Private Washer and Dryer - 2 driveway parking spaces - All Bedrooms have large closets - 2 minute walk from village center: Restaurants, cafes, shops, bars, festivals, farmers market - Tenant pays Gas and Electricity - Available Immediately - Sorry, no pets Tenant pays gas and electricity",
        "imageUrls": "./assets/house1.jpg",
        "extras": "Pets are not allowed"
    },
    {
        "id": 1,
        "propertyId": "P1006",
        "sellerId": "U1001",
        "visitors": [],
        "pincode": 570001,
        "propertyType": "Rent",
        "propertyOwnership": "Owner",
        "buildingType": "House",
        "noOfBathrooms": 2,
        "noOfBedrooms": 2,
        "noOfBalconies": 1,
        "furnishing": "Fully Furnished",
        "availability": "Ready to move",
        "lifts": true,
        "ac": true,
        "heater": false,
        "maintenenceStaff": true,
        "visitorParking": true,
        "IntercomFacility": false,
        "wifi": true,
        "fireAlarm": false,
        "WaterPurifier": false,
        "PowerBackup": true,
        "WaterSupplyFor24Hours": true,
        "CloseToSchool": true,
        "CloseToHospital": false,
        "CloseToRailwayStation": true,
        "CloseToBusStand": true,
        "CloseToAirport": false,
        "CloseToBank": true,
        "CloseToPark": false,
        "status": "Available",
        "address": "Old lakshami colony,street no 5,Delhi",
        "price": 15000,
        "Advance": 50000,
        "transactionType": "New",
        "ageOfProperty": "1 year old property",
        "availabilityBy": "Within 2 weeks",
        "totalFloors": 10,
        "PropertyFloor": 5,
        "propertyArea": 1200,
        "poojaRoom": true,
        "servantRoonm": true,
        "noofCoveredParking": 1,
        "noOfOpenParking": 1,
        "description": "Recently renovated and restored. Upper Unit - 2 Bedrooms 2 Full Bathroom - New kitchen, appliances, bathroom and flooring - Kitchen appliances included: Refrigerator, Gas Oven/ Range, Dishwasher, Over the Range Microwave - Private Washer and Dryer - 2 driveway parking spaces - All Bedrooms have large closets - 2 minute walk from village center: Restaurants, cafes, shops, bars, festivals, farmers market - Tenant pays Gas and Electricity - Available Immediately - Sorry, no pets Tenant pays gas and electricity",
        "imageUrls": "./assets/house1.jpg",
        "extras": "Pets are not allowed"
    }
]

const wishlist = [
    {
        "id": 1001,
        "properties": []
    },
    {
        "id": 1002,
        "properties": []
    },
    {
        "id": 1003,
        "properties": []
    }
]

exports.setupDb = async ()  =>  {
    let Data = await collection.getPropertyCollection();
    await Data.deleteMany();
    let InsertedData = await Data.insertMany(propertyDb);
    let UserCollection = await collection.getUserCollection();
    await UserCollection.deleteMany();
    let UserInsertedData = await UserCollection.insertMany(userDb);
    let BookingCollection = await collection.getbookingCollection();
    await BookingCollection.deleteMany();
    let BookingInsertedData = await BookingCollection.insertMany(bookings);
    let WishlistCollection = await collection.getWishlist();
    await WishlistCollection.deleteMany();
    let WishlistInsertedData = await WishlistCollection.insertMany(wishlist);

    if (InsertedData && UserInsertedData && BookingInsertedData && WishlistInsertedData) {
        return "Insertion Successful"
    }
    else {
        let err = new Error("Insertion Failed")
        err.status = 500;
        throw err;
    }
}